CREATE TABLE GOLOSINA(
    IDGOLOSINA INT NOT NULL,
    COMBO VARCHAR(80) NOT NULL,
    PRECIO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    TOTAL INT NOT NULL,
    PRIMARY KEY (IDGOLOSINA)
);

CREATE TABLE TICKET(
    IDTICKET INT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(90),
    PELICULAS VARCHAR(60) NOT NULL,
    PRECIO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    DESCUENTO DOUBLE NOT NULL,
    TOTAL DOUBLE NOT NULL,
    PRIMARY KEY (IDTICKET)
);



