
package microproyecto;


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
    
public class Golosinas extends javax.swing.JInternalFrame {
Conexion conex = new Conexion();
    Connection con2;
    /**
     * Creates new form Golosinas
     */
    public Golosinas() {
        initComponents();  
        Principal.controlArt = true;
        cargarCombos();
       
    }
public void cargarCombos(){
        this.JBCcombos.removeAllItems();
        this.JBCcombos.addItem("Seleccione un Combo");
        this.JBCcombos.addItem("Combo Economico");
        this.JBCcombos.addItem("Combo Cinepolis");
        this.JBCcombos.addItem("Combo VIP");
        this.JtxtCantidad.setText("");

}
public void limpiar(){

        this.JtxtSubtotal.setText("");
        this.JtxtISV.setText("");
        this.JtxtTotal.setText("");
        this.JtxtCantidad.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        JBCcombos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtxtCantidad = new javax.swing.JTextField();
        JtxtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JtxtSubtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JtxtISV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JtxtTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Jlimagen = new javax.swing.JLabel();
        JbtnCalcular = new javax.swing.JButton();
        jBimprimirFcatura = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JtxtIDventa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("Enviar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        JBCcombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCcombosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Combos ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cantidad ");

        JtxtPrecio.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Sub Total");

        JtxtSubtotal.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("ISV (15%)");

        JtxtISV.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total");

        JtxtTotal.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        Jlimagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        JbtnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JbtnCalcular.setText("Calcular");
        JbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCalcularActionPerformed(evt);
            }
        });

        jBimprimirFcatura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBimprimirFcatura.setText("Imprimir Factura");
        jBimprimirFcatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirFcaturaActionPerformed(evt);
            }
        });

        jButton1.setText("VER TABLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microproyecto/iconos/cinepolis.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID Venta:");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCcombos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(JtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(JtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(JtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(JtxtISV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(48, 48, 48)
                        .addComponent(JtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBimprimirFcatura, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(29, 29, 29)
                            .addComponent(JtxtIDventa))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JtxtIDventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(JBCcombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(JtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(JtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(JtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(JtxtISV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10))
                            .addComponent(JtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(JbtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBimprimirFcatura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCcombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCcombosActionPerformed
        
        
        if(this.JBCcombos.getSelectedItem() == "Combo Economico"){
            Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microproyecto/iconos/combo Economico.jpg")));
        this.JtxtPrecio.setText("130");
       limpiar();
        } else{
            if(this.JBCcombos.getSelectedItem() == "Combo Cinepolis"){
            Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microproyecto/iconos/combo CineLatino.jpg")));
        this.JtxtPrecio.setText("180");
       limpiar();
        }else{
        if(this.JBCcombos.getSelectedItem() == "Combo VIP"){
            Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microproyecto/iconos/combo VIP.jpg")));
        this.JtxtPrecio.setText("230");
        limpiar();
        }else{
        Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        this.JtxtPrecio.setText("0");
        limpiar();
        }
        
        }
        }
       
    }//GEN-LAST:event_JBCcombosActionPerformed

    public void ingresar(){
    
     con2 = conex.Conectar();

           
                try
                {
                    Statement insertar = con2.createStatement();
                    String query = "INSERT INTO GOLOSINA (IDGOLOSINA, COMBO, PRECIO, CANTIDAD, TOTAL)"
                    + " VALUES (" + this.JtxtIDventa.getText() + ",'" + this.JBCcombos.getSelectedItem()+"',"
                            + this.JtxtPrecio.getText() +"," + this.JtxtCantidad.getText()+"," + this.JtxtTotal.getText() + ")";
                    insertar.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "¡VENTA ALMACENADA CORRECTAMENTE!");
                  limpiar();
                   Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                    this.JtxtPrecio.setText("0");
                    this.JtxtIDventa.setText("");
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, "Error: " + ex);
                }
            
    
    
    }
    
    private void JbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCalcularActionPerformed
        
        int cantidad;
        Double precio,subtotal, isv,total;
if(this.JBCcombos.getSelectedItem()== "Seleccione un Combo"){

JOptionPane.showMessageDialog(null, "Debe Selecionar Un Combo Porfavor");

}else{  
         if(this.JtxtCantidad.getText().equals(""))
         {
             this.JtxtCantidad.setBackground(Color.red);
             JOptionPane.showMessageDialog(null, "Debe De Ingresar Cantidad de Combos");
             
         }
       else
         {
             try{
                 String id = this.JtxtIDventa.getText();
                 
                 precio = Double.parseDouble(this.JtxtPrecio.getText());
                 cantidad = Integer.parseInt(this.JtxtCantidad.getText());
                 
                 calculosgolosinas golo = new calculosgolosinas(id,precio,cantidad);
              
                 this.JtxtSubtotal.setText(""+golo.subtotal());
                 this.JtxtISV.setText(""+golo.isv());
                 this.JtxtTotal.setText(""+golo.TOTAL());
                 ingresar();
                 
             } catch(NumberFormatException ex)
             {
                 JOptionPane.showMessageDialog(null, "ERROR, deben ser solo numeros");
                 this.JtxtCantidad.setText("");
                 
             }
             
         }
        
    
}    
    }//GEN-LAST:event_JbtnCalcularActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        Principal.controlArt = false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jBimprimirFcaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirFcaturaActionPerformed
         if(this.JtxtCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Primero Calcule los datos....Gracias..");
            this.JtxtCantidad.setBackground(Color.red);
        }else{
       JOptionPane.showMessageDialog(null,
               "PRECIO:"+this.JtxtPrecio.getText()+"\n"+"CANTIDAD:"+this.JtxtCantidad.getText()+"\n"+
               "SUBTOTAL:"+this.JtxtSubtotal.getText()+"\n"+"ISV(15%):"+this.JtxtISV.getText()+"\n"+
               "\n"+"TOTAL:"+this.JtxtTotal.getText(),"FACTURA GOLOSINAS CINEPOLIS", JOptionPane.INFORMATION_MESSAGE);
        }
        Jlimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        this.JtxtPrecio.setText("");
        limpiar();
    }//GEN-LAST:event_jBimprimirFcaturaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TablaGolosinas tg = new TablaGolosinas();
        tg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBCcombos;
    private javax.swing.JButton JbtnCalcular;
    private javax.swing.JLabel Jlimagen;
    private javax.swing.JTextField JtxtCantidad;
    private javax.swing.JTextField JtxtIDventa;
    private javax.swing.JTextField JtxtISV;
    private javax.swing.JTextField JtxtPrecio;
    private javax.swing.JTextField JtxtSubtotal;
    private javax.swing.JTextField JtxtTotal;
    private javax.swing.JButton jBimprimirFcatura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
